### ISSUE TITLE
Filtering with jq

### ISSUE THREAD

**Issue by SohamChakraborty** [nccgroup/aws-inventory#23]
Hi,

So I am trying to filter the data using jq. What I am after is the instance ids of the ec2 instances. I got to the part where I can see all the outputs of the `text` key, but then I am not able to drill down further. This is not really a tool specific help, but I am quite sure that some jq filtering examples in the readme.md file may prove beneficial.
If I run `jq '.responses[].children[].children[].children[].text'` on the aws-inventory/gui/<whatever_data.json> file, I get this: 

```
"DescribeCustomerGateways (1)"
"DescribeIdFormat (1)"
"DescribeNetworkAcls (1)"
"DescribePrefixLists (1)"
"DescribeSpotInstanceRequests"
"DescribeVpcClassicLink (1)"
<SNIPPED>
```
Now, I want to drill further down and and see things inside of `"DescribeInstances (1)"`. How is that possible? 

P.S. I ran the script with `--service ec2` only.

**Comment by bitsandsalsa** [comment]
If you filter on one region and one service on the commandline with `--services` and `--regions`, then the following should get what you want:
`jq '.responses[].children[].children[].children[] | select(.text | startswith("DescribeInstances"))' file.json`
