### ISSUE TITLE
Error: Connection pool is full

### ISSUE THREAD

**Issue by bluecanarybe** [nccgroup/aws-inventory#29]
My progress is stuck halfway (6847/12966), receiving following debug output:

WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ec2.us-east-1.amazonaws.com

**Comment by bitsandsalsa** [comment]
This is a warning about efficiency and shouldn't be stalling progress. See boto/botocore#766. However, it is likely an indication of a bug elsewhere around resource contention.

**Comment by aleon1220** [comment]
all of the threads in botocore point to
`botocore.client.Config(max_pool_connections=X)`

check
https://github.com/boto/botocore/pull/1026#issuecomment-409284060

**Comment by aleon1220** [comment]
a PR is open to address this. 
refer to https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html
- add to max_pool_connections  config.py
- set the config in the invoker.py
`max_pool_connections=config.CLIENT_MAX_POOL_CONNECTIONS`

**Comment by bitsandsalsa** [comment]
Fixed by #30
