### ISSUE TITLE
Unknown encoding: raw-unicode-escape

### ISSUE THREAD

**Issue by lllama** [nccgroup/aws-inventory#3]
I get this error when it tries to save the results:

```
    self.write(UNICODE + obj.encode('raw-unicode-escape') + '\n')
LookupError: unknown encoding: raw-unicode-escape
```

Looks like it comes from this line:
```
 pickle.dump(self._response_store, fp)

```

**Comment by bitsandsalsa** [comment]
* What version of Python are you using? `python -V`
* Could you please paste a full stack trace?
* What OS?
* Does the following result in an error: `print ''.encode('raw-unicode-escape')`?
* This functionality is in serializing the responses and exceptions to a file. It was really meant for debugging. The exceptions file could indicate an issue you might want to resolve.

Try these changes: 9604419a2322b41683db2731064b64d2b878432d

**Comment by chilithomas** [comment]
Hello bitsandsalsa I get the same error at the assumed end of the script. It's Python 2.7 running on Ubuntu 18 Desktop. I don't see that print statement. If it's just for debugging, where is the output?
![image](https://user-images.githubusercontent.com/40802133/42911332-70404d5c-8a9f-11e8-8478-9514a9dfa26c.png)
