### ISSUE TITLE
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation

### ISSUE THREAD

**Issue by Leectan** [nccgroup/aws-inventory#34]
**Describe the bug**
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam::123456789012:user/aws-user is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::210987654321:role/cross-account-assume-role

**To Reproduce**
1. Go to 'python aws_inventory.py --profile profile1'

**Expected behavior**
Should run all the way and output a file.

**Screenshots / Stack Traces**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Python Version python 2.7.16

**Comment by bitsandsalsa** [comment]
@Leectan I think your configuration is set to use an IAM role. See [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html) and [Boto](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/quickstart.html#configuration) configuration docs. The inventory tool does not do any assuming of roles.
